#macro PATH_DUMMY_DATA ".\\data\\dummy\\"
#macro UI_MENU_SLOT_HEIGHT 32
#macro UI_MENU_WIDTH 480
#macro UI_MENU_START_Y 32
#macro UI_MENU_START_X 32
#macro BATTLEFIELD_SIZE 256
#macro buffer_datatype buffer_u32
#macro c_brown make_color_rgb(139, 69, 19)
#macro c_exp c_blue
#macro c_health_high c_green
#macro c_health_low c_red
#macro c_health_mid c_yellow
#macro c_pink make_color_rgb(255, 105, 180)
#macro DEBUG true
#macro IMPORT_EXTENSION_DATA ".dddd"
#macro IMPORT_EXTENSION_MAP ".dddm"
#macro LOG_FILE "log.txt"
#macro MAX_LEVEL 100
#macro THOUSAND 1000
#macro MILLION 1000000
#macro MOVE_LIMIT 4
#macro OPTIONS_INI ".\\ddd.ini"
#macro PATH_AUTOTILE ".\\data\\graphics\\autotiles\\"
#macro PATH_BATTLER ".\\data\\graphics\\battlers\\"
#macro PATH_DATA ".\\data\\stuff\\"
#macro PATH_LANGUAGE ".\\data\\strings.txt"
#macro PATH_MAP ".\\data\\stuff\\maps\\"
#macro PATH_FONT ".\\data\\graphics\\fonts\\"
#macro PATH_TILESET ".\\data\\graphics\\tilesets\\"
#macro PAWN_ANIMATION_FRAMES_PER_SECOND 4
#macro SERIALIZE_DATA 1
#macro SERIALIZE_MAP 0
#macro STAT_MOD_LIMIT 6
#macro T buffer_f32
#macro TEXTURE_SIZE 4096
#macro TILE_DEPTH 32
#macro TILE_HEIGHT 32
#macro TILE_WIDTH 32
#macro TYPE_IMMUNE 0
#macro TYPE_RESISTED 0.5
#macro TYPE_WEAK 2
#macro UI_BATTLE_HUD_BUFFER_X 32
#macro UI_BATTLE_HUD_BUFFER_Y 64
#macro UI_BATTLE_HUD_HEIGHT 128
#macro UI_BATTLE_HUD_WIDTH 400
#macro UI_TEXT_BOX_HEIGHT 160
#macro UI_TEXT_BOX_OFFSET_H 32
#macro UI_TEXT_BOX_OFFSET_W 32
#macro UI_TEXT_BOX_WIDTH W
#macro UI_TEXT_OPTION_BUFFER_W 32
#macro UI_TEXT_WIDTH W * 2 / 3
#macro USE_DUMMY_DATA true